require_relative 'auto_from_methods'

require_relative 'chat'
require_relative 'user'
require_relative 'group_chat'
require_relative 'message'
require_relative 'photo_size'
require_relative 'audio'
require_relative 'document'
require_relative 'video'
require_relative 'contact'
require_relative 'location'
require_relative 'update'
require_relative 'date'
require_relative 'sticker'
